onlyBuiltDependencies:
  - esbuild
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.3.3
  vitest: 4.1.11
  vite-plus: 1.0.0
overrides:
  vite: "catalog:"
  vitest: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
allowBuilds:
  "@swc/core": true
  workerd: true
  esbuild: true
  fallow: true
  unrs-resolver: true
