import {defineConfig} from "vite-plus";
import {resolve} from "node:path";
import react from "@vitejs/plugin-react";

export default defineConfig({
	fmt: {
		semi: true,
		singleQuote: false,
		useTabs: true,
		tabWidth: 4,
		printWidth: 120,
		bracketSpacing: false,
		trailingComma: "all",
		arrowParens: "always",
		overrides: [
			{
				files: [".yamllint.yaml", "**/*.yaml", "**/*.yml"],
				options: {
					useTabs: false,
					tabWidth: 2,
				},
			},
		],
	},
	run: {
		tasks: {
			"test:run": {
				command:
					"node node_modules/vitest/dist/cli.js run && node node_modules/vitest/dist/cli.js run --config vitest.worker.config.ts && node node_modules/playwright/cli.js test --config playwright.config.ts",
				input: [{auto: true}, "!node_modules/.experimental-vitest-cache/**"],
				output: [],
			},
		},
	},
	staged: {
		"*": "vp check --fix",
	},
	lint: {
		plugins: [],
		categories: {
			correctness: "off",
		},
		env: {
			builtin: true,
		},
		ignorePatterns: ["dist", "build", "storybook-static", ".llm/**", "vitest.shims.d.ts"],
		overrides: [
			{
				files: ["public/**/*.{ts,tsx}"],
				globals: {
					ServiceWorkerGlobalScope: "readonly",
					ExtendableEvent: "readonly",
				},
			},
			{
				files: ["vite.config.ts", "vitest.config.ts"],
				globals: {
					process: "readonly",
				},
			},
			{
				files: ["**/*.test.{js,jsx,ts,tsx}", "**/*.spec.{js,jsx,ts,tsx}", "**/setupTests.{js,ts}"],
				globals: {
					vi: "readonly",
				},
				env: {
					browser: true,
					jest: true,
				},
			},
			{
				files: ["**/*.{js,jsx}"],
				rules: {
					"getter-return": "error",
					"no-undef": "error",
					"no-unreachable": "error",
					"constructor-super": "error",
					"for-direction": "error",
					"no-async-promise-executor": "error",
					"no-case-declarations": "error",
					"no-class-assign": "error",
					"no-compare-neg-zero": "error",
					"no-cond-assign": "error",
					"no-const-assign": "error",
					"no-constant-binary-expression": "error",
					"no-constant-condition": "error",
					"no-control-regex": "error",
					"no-debugger": "error",
					"no-delete-var": "error",
					"no-dupe-class-members": "error",
					"no-dupe-else-if": "error",
					"no-dupe-keys": "error",
					"no-duplicate-case": "error",
					"no-empty": "error",
					"no-empty-character-class": "error",
					"no-empty-pattern": "error",
					"no-empty-static-block": "error",
					"no-ex-assign": "error",
					"no-extra-boolean-cast": "error",
					"no-fallthrough": "error",
					"no-func-assign": "error",
					"no-global-assign": "error",
					"no-import-assign": "error",
					"no-invalid-regexp": "error",
					"no-irregular-whitespace": "error",
					"no-loss-of-precision": "error",
					"no-misleading-character-class": "error",
					"no-new-native-nonconstructor": "error",
					"no-nonoctal-decimal-escape": "error",
					"no-obj-calls": "error",
					"no-prototype-builtins": "error",
					"no-redeclare": "error",
					"no-regex-spaces": "error",
					"no-self-assign": "error",
					"no-setter-return": "error",
					"no-shadow-restricted-names": "error",
					"no-sparse-arrays": "error",
					"no-this-before-super": "error",
					"no-unassigned-vars": "error",
					"no-unexpected-multiline": "error",
					"no-unsafe-finally": "error",
					"no-unsafe-negation": "error",
					"no-unsafe-optional-chaining": "error",
					"no-unused-labels": "error",
					"no-unused-private-class-members": "error",
					"no-unused-vars": [
						"error",
						{
							varsIgnorePattern: "^([A-Z_]|_)",
							argsIgnorePattern: "^_",
							caughtErrorsIgnorePattern: "^_",
						},
					],
					"no-useless-backreference": "error",
					"no-useless-catch": "error",
					"no-useless-escape": "error",
					"no-with": "error",
					"preserve-caught-error": "error",
					"require-yield": "error",
					"use-isnan": "error",
					"valid-typeof": "error",
					"react-hooks/rules-of-hooks": "error",
					"react-hooks/exhaustive-deps": "error",
					eqeqeq: ["error", "smart"],
					"react/only-export-components": [
						"warn",
						{
							allowConstantExport: true,
						},
					],
				},
				env: {
					es2020: true,
					browser: true,
					jest: true,
				},
				plugins: ["react"],
			},
			{
				files: ["**/*.{ts,tsx}"],
				rules: {
					"getter-return": "error",
					"no-unreachable": "error",
					"@typescript-eslint/ban-ts-comment": [
						"error",
						{
							minimumDescriptionLength: 10,
						},
					],
					"no-array-constructor": "error",
					"@typescript-eslint/no-duplicate-enum-values": "error",
					"@typescript-eslint/no-dynamic-delete": "error",
					"@typescript-eslint/no-empty-object-type": "error",
					"@typescript-eslint/no-explicit-any": "off",
					"@typescript-eslint/no-extra-non-null-assertion": "error",
					"@typescript-eslint/no-extraneous-class": "error",
					"@typescript-eslint/no-invalid-void-type": "error",
					"@typescript-eslint/no-misused-new": "error",
					"@typescript-eslint/no-namespace": "error",
					"@typescript-eslint/no-non-null-asserted-nullish-coalescing": "error",
					"@typescript-eslint/no-non-null-asserted-optional-chain": "error",
					"@typescript-eslint/no-non-null-assertion": "error",
					"@typescript-eslint/no-require-imports": "error",
					"@typescript-eslint/no-this-alias": "error",
					"@typescript-eslint/no-unnecessary-type-constraint": "error",
					"@typescript-eslint/no-unsafe-declaration-merging": "error",
					"@typescript-eslint/no-unsafe-function-type": "error",
					"no-unused-expressions": "error",
					"no-unused-vars": [
						"error",
						{
							varsIgnorePattern: "^([A-Z_]|_)",
							argsIgnorePattern: "^_",
							caughtErrorsIgnorePattern: "^_",
						},
					],
					"@typescript-eslint/no-useless-constructor": "error",
					"no-var": "error",
					"@typescript-eslint/no-wrapper-object-types": "error",
					"@typescript-eslint/prefer-as-const": "error",
					"@typescript-eslint/prefer-literal-enum-member": "error",
					"@typescript-eslint/prefer-namespace-keyword": "error",
					"@typescript-eslint/triple-slash-reference": "error",
					"@typescript-eslint/unified-signatures": "error",
					"@typescript-eslint/no-unsafe-type-assertion": "error",
					"@typescript-eslint/no-floating-promises": "error",
					"@typescript-eslint/no-misused-promises": "error",
					"@typescript-eslint/await-thenable": "error",
					"@typescript-eslint/require-await": "error",
					"@typescript-eslint/return-await": ["error", "error-handling-correctness-only"],
					"@typescript-eslint/only-throw-error": "error",
					"@typescript-eslint/switch-exhaustiveness-check": "error",
					"@typescript-eslint/no-unnecessary-type-assertion": "error",
					"@typescript-eslint/prefer-nullish-coalescing": "error",
					"@typescript-eslint/no-unsafe-enum-comparison": "error",
					"@typescript-eslint/no-unsafe-unary-minus": "error",
					"@typescript-eslint/no-misused-spread": "error",
					"@typescript-eslint/no-array-delete": "error",
					"@typescript-eslint/no-for-in-array": "error",
					"@typescript-eslint/no-implied-eval": "error",
					"@typescript-eslint/restrict-plus-operands": "error",
					"@typescript-eslint/no-mixed-enums": "error",
					"@typescript-eslint/use-unknown-in-catch-callback-variable": "error",
					"@typescript-eslint/consistent-type-exports": "error",
					"@typescript-eslint/no-redundant-type-constituents": "error",
					"@typescript-eslint/no-unnecessary-boolean-literal-compare": "error",
					"@typescript-eslint/no-unnecessary-type-parameters": "error",
					"@typescript-eslint/no-unnecessary-type-conversion": "error",
					"@typescript-eslint/no-useless-default-assignment": "error",
					"@typescript-eslint/prefer-find": "error",
					"@typescript-eslint/prefer-includes": "error",
					"@typescript-eslint/prefer-string-starts-ends-with": "error",
					"@typescript-eslint/prefer-reduce-type-parameter": "error",
					"@typescript-eslint/prefer-return-this-type": "error",
					"@typescript-eslint/related-getter-setter-pairs": "error",
					"@typescript-eslint/non-nullable-type-assertion-style": "error",
					"@typescript-eslint/prefer-promise-reject-errors": "error",
					"@typescript-eslint/prefer-optional-chain": "error",
					"@typescript-eslint/no-unsafe-return": "error",
					"@typescript-eslint/no-unnecessary-template-expression": "error",
					"no-promise-executor-return": "error",
					"no-negated-condition": "error",
					"@typescript-eslint/no-confusing-void-expression": "error",
					"@typescript-eslint/promise-function-async": "error",
					"@typescript-eslint/dot-notation": ["error", {allowIndexSignaturePropertyAccess: true}],
					"@typescript-eslint/consistent-return": "error",
					"@typescript-eslint/prefer-readonly": "error",
					"@typescript-eslint/no-deprecated": "error",
					"import/no-cycle": "error",
					"import/no-self-import": "error",
					"import/no-duplicates": "error",
					"@typescript-eslint/no-unsafe-assignment": "error",
					"@typescript-eslint/no-unsafe-member-access": "error",
					"@typescript-eslint/no-unsafe-call": "error",
					"@typescript-eslint/no-unsafe-argument": "error",
					"@typescript-eslint/no-unnecessary-condition": ["error", {allowConstantLoopConditions: true}],
					"@typescript-eslint/strict-boolean-expressions": "error",
					"react-hooks/rules-of-hooks": "error",
					"react-hooks/exhaustive-deps": "error",
					eqeqeq: ["error", "smart"],
					"react/only-export-components": [
						"warn",
						{
							allowConstantExport: true,
						},
					],
				},
				env: {
					es2020: true,
					browser: true,
					jest: true,
				},
				plugins: ["typescript", "react", "import"],
			},
			{
				files: ["**/*.stories.@(ts|tsx|js|jsx|mjs|cjs)", "**/*.story.@(ts|tsx|js|jsx|mjs|cjs)"],
				rules: {
					"react-hooks/rules-of-hooks": "off",
					"import-x/no-anonymous-default-export": "off",
					"storybook/await-interactions": "error",
					"storybook/context-in-play-function": "error",
					"storybook/default-exports": "error",
					"storybook/hierarchy-separator": "warn",
					"storybook/no-redundant-story-name": "warn",
					"storybook/no-renderer-packages": "error",
					"storybook/prefer-pascal-case": "warn",
					"storybook/story-exports": "error",
					"storybook/use-storybook-expect": "error",
					"storybook/use-storybook-testing-library": "error",
				},
				jsPlugins: ["eslint-plugin-storybook"],
				plugins: ["react", "import"],
			},
			{
				files: [".storybook/main.@(js|cjs|mjs|ts)"],
				rules: {
					"storybook/no-uninstalled-addons": "error",
				},
				jsPlugins: ["eslint-plugin-storybook"],
			},
			{
				files: ["**/*.test.{ts,tsx}", "**/*.spec.{ts,tsx}"],
				rules: {
					"@typescript-eslint/no-non-null-assertion": "off",
					"@typescript-eslint/no-unsafe-type-assertion": "off",
					"@typescript-eslint/no-unsafe-assignment": "off",
					"@typescript-eslint/no-unsafe-member-access": "off",
					"@typescript-eslint/no-unsafe-call": "off",
					"@typescript-eslint/no-unsafe-argument": "off",
					"vitest/no-focused-tests": "error",
					"vitest/no-disabled-tests": "error",
					"vitest/no-identical-title": "error",
					"vitest/valid-expect": "error",
					"vitest/require-mock-type-parameters": "error",
					"vitest/require-to-throw-message": "error",
				},
				plugins: ["typescript", "vitest"],
			},
		],
		options: {
			typeAware: true,
			typeCheck: true,
		},
	},
	plugins: [react()],
	base: process.env["VITE_BASE_PATH"] ?? "/",
	root: ".",
	build: {
		outDir: "dist",
		rolldownOptions: {
			input: {
				main: resolve(import.meta.dirname, "index.html"),
			},
		},
		sourcemap: true,
	},
	server: {
		port: 3000,
		allowedHosts: process.env["VITE_ALLOWED_HOSTS"]?.split(",") ?? [],
		// The Worker API runs under `wrangler dev` (port 8787) during local development.
		proxy: {
			"/api": {target: "http://localhost:8787", ws: true},
		},
	},
});
